---
name: Build and Test

on:
  push:
    branches:
      - $default-branch
      - develop
  pull_request:
    branches:
      - $default-branch
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Build"
          cat <<EOF >foo.sh
          #!/bin/bash
          echo "Hello World: Version ${{ github.sha }}"
          exit 0
          EOF
          chmod u+x foo.sh
      - name: Archive
        run: tar -cO foo.sh |gzip -v9 >"foo-$(git rev-parse --short "${{ github.sha }}").sh.tar.gz"
      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Foo Artifact
          path: foo-*.sh.tar.gz
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: "Get Build"
        uses: "actions/download-artifact@v3"
        with:
          name: Foo Artifact
      - name: Install
        run: gzip -cd foo-*.sh.tar.gz |tar -xvf-
      - name: "Test"
        run: |
          ./foo.sh |grep -e "Hello"
          ./foo.sh |grep -e "World"
